# Generated by Django 4.0.3 on 2022-03-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('discribtion', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=350)),
                ('aminity', models.CharField(choices=[('hairdryer', 'hairdryer'), ('laundry', 'laundry')], max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_city', to='booking.destination')),
            ],
        ),
    ]
