# Generated by Django 4.0.3 on 2022-03-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_room_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_reserve',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.hotel'),
            preserve_default=False,
        ),
    ]
