# Generated by Django 4.0.3 on 2022-03-27 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_room_reserve_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_reserve',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
