# Generated by Django 4.0.3 on 2022-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_room_reserve_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_reserve',
            name='total_days',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room_reserve',
            name='total_price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
