# Generated by Django 4.0.3 on 2022-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_room_reserve_total_days_room_reserve_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
            ],
        ),
    ]
