# Generated by Django 4.0.3 on 2022-04-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_rate_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
